[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22.21.1"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "https://www.datadev.es/:splat"
  status = 301
  force = true